- name: Install Direwolf
  package:
    name: "{{ direwolf_packages }}"
    state: present

- name: Install direwolf configuration
  notify: restart-direwolf
  template:
    src: direwolf.j2.conf
    dest: /etc/radio/direwolf.conf

- name: Install systemd units
  notify: reload-systemd
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item|basename }}"
    owner: root
    mode: "0644"
  loop: "{{ query('fileglob', 'systemd/*') }}"

- name: Install service helper
  notify: restart-direwolf
  copy:
    src: direwolf-service-helper.sh
    dest: "/usr/libexec/radio/direwolf-service-helper.sh"
    mode: "0755"

- name: Install environment settings
  notify: restart-direwolf
  template:
    src: direwolf.j2.env
    dest: /etc/radio/direwolf.env
    group: radio
    mode: "0775"
    force: "{{ force_replace }}"
