- name: Install hamlib
  tags: [hamlib]
  package:
    name: "{{ hamlib_packages }}"
    state: present

- name: Install hamlib configuration
  tags: [hamlib]
  notify: restart-rigctld
  template:
    src: hamlib.j2.env
    dest: /etc/radio/hamlib.env
    group: radio
    mode: "0755"

- name: Install systemd units
  tags: [hamlib]
  notify:
    - reload-systemd
    - restart-rigctld
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item|basename }}"
    owner: root
    mode: "0644"
  loop: "{{ query('fileglob', 'systemd/*') }}"

- name: Enable rigctld
  tags: [hamlib]
  service:
    name: rigctld
    enabled: true
    state: started
